name: Tag Checks
description: "Check repository for tags"

inputs:
  tag_name:
    description: "Tag name"
    required: true

outputs:
  has_tag:
    description: "Has the tag name provided"
    value: ${{ steps.tagged.outputs.tagged }}

runs:
  using: composite
  steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch tags
        shell: bash
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Check for tag
        shell: bash
        id: tagged
        run: git show-ref --tags --verify -- "refs/tags/${{ inputs.tag_name }}" && echo "tagged=0" >>$GITHUB_OUTPUT || echo "tagged=1" >>$GITHUB_OUTPUT

      - name: Does not have a tag
        if: steps.tagged.outputs.tagged == 0
        shell: bash
        run: echo No Tag

      - name: Does have a tag
        if: steps.tagged.outputs.tagged == 1
        shell: bash
        run: echo Existing Tag



