name: Tag Checks
description: "Check repository for tags"

inputs:
  github-token:
    description: "Github Token"
    required: true
  branch-name:
    description: "Current Branch"
    required: true

outputs:
  tag:
    description: "Tag name"
    value: ${{ steps.package-version.outputs.result }}

runs:
  using: composite
  steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}

      - name: Get Version
        id: package-version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return require('./package.json').version

      - name: Check for tag
        shell: bash
        id: tagged
        run: git show-ref --tags --verify --quiet -- "refs/tags/${{ steps.package-version.outputs.result }}" && echo "tagged=0" >>$GITHUB_OUTPUT || echo "tagged=1" >>$GITHUB_OUTPUT

      - name: Already has this tag
        if: steps.tagged.outputs.tagged == 0
        uses: actions/github-script@v6
        with:
          github-token: ${{ inputs.github-token }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Tag check failed",
              body: "The tag already exists",
              labels: ['${{ steps.package-version.outputs.result }}', 'Tag Exists']
            core.setFailed('Tag check FAILED')

